<?xml version="1.0" encoding="ASCII"?>

<!-- oks-schema version 2.0 -->


<!DOCTYPE oks-schema [
  <!ELEMENT oks-schema (info, (include)?, (comments)?, (class)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-includes CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "schema"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT class (superclass | attribute | relationship | method)*>
  <!ATTLIST class
      name CDATA #REQUIRED
      description CDATA ""
      is-abstract (yes|no) "no"
  >
  <!ELEMENT superclass EMPTY>
  <!ATTLIST superclass name CDATA #REQUIRED>
  <!ELEMENT attribute EMPTY>
  <!ATTLIST attribute
      name CDATA #REQUIRED
      description CDATA ""
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class) #REQUIRED
      range CDATA ""
      format (dec|hex|oct) "dec"
      is-multi-value (yes|no) "no"
      init-value CDATA ""
      is-not-null (yes|no) "no"
  >
  <!ELEMENT relationship EMPTY>
  <!ATTLIST relationship
      name CDATA #REQUIRED
      description CDATA ""
      class-type CDATA #REQUIRED
      low-cc (zero|one) #REQUIRED
      high-cc (one|many) #REQUIRED
      is-composite (yes|no) #REQUIRED
      is-exclusive (yes|no) #REQUIRED
      is-dependent (yes|no) #REQUIRED
  >
  <!ELEMENT method (method-implementation*)>
  <!ATTLIST method
      name CDATA #REQUIRED
      description CDATA ""
  >
  <!ELEMENT method-implementation EMPTY>
  <!ATTLIST method-implementation
      language CDATA #REQUIRED
      prototype CDATA #REQUIRED
      body CDATA ""
  >
]>

<oks-schema>

<info name="" type="" num-of-includes="2" num-of-items="2" oks-format="schema" oks-version="oks-06-03-04 built &quot;Sep 27 2011&quot;" created-by="glehmann" created-on="pcatd86" creation-time="20030820T141734" last-modified-by="rhauser" last-modified-on="msu-pc7.cern.ch" last-modification-time="20110927T151606"/>

<include>
 <file path="daq/schema/core.schema.xml"/>
 <file path="daq/schema/df.schema.xml"/>
 <file path="daq/schema/monsvc_config.schema.xml"/>
</include>


 <class name="HLTSVApplication" description="Describes the HLT Supervisor.">
  <superclass name="RunControlApplication"/>
  <superclass name="PublishingApplication"/>
  <superclass name="Resource"/>
  <relationship name="Configuration" class-type="HLTSVConfiguration" low-cc="one" high-cc="one" is-composite="no" is-exclusive="no" is-dependent="no"/>
 </class>

 <class name="HLTSVConfiguration">
  <attribute name="L1Source" type="enum" range="internal,preloaded,filar,assembler" init-value="internal" is-not-null="yes"/>
  <attribute name="Timeout" description="Timeout for HLT processing in milliseconds." type="u32" init-value="10000" is-not-null="yes"/>
  <attribute name="NumberOfAssignThreads" description="Number of assignment threads." type="u32" init-value="8" is-not-null="yes"/>
  <attribute name="ClearGrouping" description="Number of L1 events grouping factor for clears" type="u32" init-value="100" is-not-null="yes"/>
  <attribute name="EventDelay" description="Event delay in microseconds." type="u32" init-value="0" is-not-null="yes"/>
 </class>

 <class name="HLTSV_DCMTest" description="A DCM dummy for the supervisor">
  <superclass name="RunControlTemplateApplication"/>
  <attribute name="L2ProcessingTime" description="Processing time for L2 in milliseconds." type="u32" init-value="50" is-not-null="yes"/>
  <attribute name="EventBuildingTime" description="Processing time for L2 in milliseconds." type="u32" init-value="50" is-not-null="yes"/>
  <attribute name="EFProcessingTime" description="Processing time for EF in milliseconds." type="u32" init-value="5000" is-not-null="yes"/>
  <attribute name="L2Acceptance" description="L2 acceptance in percent" type="u32" init-value="5" is-not-null="yes"/>
 </class>
 

</oks-schema>
